Repository Readme-Workflows/readme-replacer, pull requests merged in 2021-07, with the labels that each got.

#1 Dev
  .github/workflows/run-build.yml
  .github/workflows/test-workflow.yml
  action.yml
  dist/index.js
  sample.json
  src/apiRequest.js
  src/app.js
  src/commitFile.js
  src/config.js
  src/customReplacer.js
  src/execute.js
  src/getDate.js
  src/replace.js
Labels: Priority: medium, Type: enhancement, skip-changelog

#3 First pass on Info
  README.md
Labels: Status: Ready, Updates: documentation

#2 feat: Add placeholders for Readme-Icons
  dist/index.js
  src/replacers.json
Labels: Priority: medium, Status: Ready, Type: enhancement, Version: minor

#6 Add missing {octicons/prDrafted} placeholder
  dist/index.js
  src/replacers.json
Labels: Status: Ready
